import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "FCFS Scheduling Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <footer className={`fixed bottom-0 left-1/2 transform -translate-x-1/2 z-20 w-full p-4 border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600 ${geistSans.variable}`}>
          <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400 text-center w-full">
            <p>
              Copyright © 2024 
              <a href="https://github.com/midoriya-2-0" className="text-gray-500 hover:underline"> Mohammed Ibrahim
              </a>. All Rights Reserved.
            </p>
          </span>
        </footer>
      </body>
    </html>
  );
}
